### ISSUE TITLE
Show notification when app is in background

### ISSUE THREAD

**Issue by ltguillaume** [tibarj/tranquilstopwatch#3]
If the app is in the background, it would be nice to be able to 1) be aware it's still running and 2) return to it easily via a notification.

Additionally, I'd like to know how the app prevents its being killed while in the background without having a foreground service (which requires a notification anyway).

**Comment by tibarj** [comment]
The app does not run in background at all. It is killed when not in foreground and this is the expected behaviour. As there is no service there is no extra consumption. In fact no service is needed to know the elapsed time: it knows a) when was last started and b) the total pause/start duration. When back in foreground, the app then calculates the total elapsed time and reschedule the next display update.
